language: node_js
node_js:
- 6.11.2
sudo: required
services:
- docker
env:
  global:
  - CXX=g++-4.8
  matrix:
  - USE_SENTRY=1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- docker pull getsentry/sentry-cli
script:
- npm install
- npm run build:dll
- npm run build
before_deploy:
- bash deploy/sentry_release.sh
- find dist/ -type f -name "*.map" -delete
- zip -r dist.zip dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Mtezw0SvrTT6095ss3z4SAPOp+eQatsS4eMjG4TkC4I7symTZXiZUyB7mUFRQU4YxMNXAjejsagwpY1fnqP9GJDsEWb8qptm9i436fMat01qKQZL4jAVOpxkjz7U5eceFnBMjtUFdfJMn/n3AkFoZTCTMV6QMUzKlDz0vYBb6AUjt811ZOvU7PiXQps3bU5UgBaIb5xgDnfaOypb+BvEIlC3KzipZnM62WDXocBlX+Jnalg3nvEmbGnSNN7yK/HIwqpT3Lm6VCwb3xr8bhZjX6ma3J1aZwzTYiOOgKfpDXiGeb3R/BXCJnsRDnZ2Nz/Ct6VqzKQLzVpNv+s2nKVsgDZw7SrGB1aYVdZQXXC9YHGpIE86KyBcnrKRMgxG9MAtXWPBYAayY91n0uN1E9iO8PSG4G7elTjmQWZrFasXtFj0roBACxCWf3P+C2CRZ3Q6RI5cdHJwi/vB+E0GN1e3qrxMge5U/pzIC0ZmAPb1Yy+rgeRpiXUEUrWIZdy8QVUG33hFjvR+69b5FozmH9wFA/B9tLikJ7rrpNg+7G9PUpkkiBeWpbihMwM85zDYYNl+nzcv0pe8o7RobZMNi9BKhPfKHmugLhWMTQbIopvhwZj6DvjQzSsfH8Au+YTU5NOiQOqJHXBt3O8s0iq6W45uurqe0LpgrOH9aB17ig+NIpY=
  file: dist.zip
  on:
    repo: jachinte/OnlineJudgeFE
    all_branches: true
    tags: true
