language: node_js
node_js:
- 6.11.2
sudo: required
services:
- docker
env:
  global:
  - CXX=g++-4.8
  matrix:
  - USE_SENTRY=1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- docker pull getsentry/sentry-cli
script:
- npm install
- npm run build:dll
- npm run build
before_deploy:
- bash deploy/sentry_release.sh
- find dist/ -type f -name "*.map" -delete
- zip -r dist.zip dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: CwmNiALAkIlpTfTR9MxgK8DLDQRtLHGm/VFcSVSmkmalH5J9Nx7xuGUMQhv+4UpolXQU+xdNOV00mG9pKFIKjX7GuHgs/Lkz5eFWKW+rXH8d1m1xkDthowwZEUqnfOGTMBeA1H/B3PWRLJZ88c2qs7LaCIs6S1oIwhwZZ2Z9hM0RWqa2/BSeoWFsDsN8EmdH1J/6w8MEHyETREleFpPeovSzcqLLo+urHm0WZ9+kBIHrtQb0J328BHsDyxL0N0YA3qBryPNkLoWXpK3m2Bmql2WI2RRGUOEjKrP3IWZCCU8F2KPlrIhjJuCcVlQ4E5Cbnm0Es67/5Rrh5vy9/EivOPZfKi3MQ1TYByrlD/MdJNL4JA3G+OacNGOj4nhsA5DzxfMmS/x/Ht3O84mIeYEWokYV3mTDqNQ+Nt9ySbOEktW2rQqXDJ0GAYcNSIyfMMPrpZJAMk052yxUu0xioYpvf0d2G8/2+Yi6/t4en9KmordeqOa49k57j0ybAJiEmye/ys0UXf69KHBxmDN2HOf/ArTt/VHx8SYzRkrdfAS61QMrRBQ6VHkQpRxjz5bSIHR+M8taj4JPo97dE7ur5013plwQx4OlrXd+fZcc41oo4RjPaJVHTnG4w5dv9OawH5qC3XRzpYxujZ+MPjr6spYtd9yYsl8wqtbvSfYD9rM897A=
  file: dist.zip
  on:
    repo: jachinte/OnlineJudgeFE
    all_branches: true
    tags: true
